### ISSUE TITLE
Speech to text functionality not working after uploading a video- multiple issues

### ISSUE THREAD

**Issue by shiprajain14** [Call-for-Code/cfc-covid-19-video-transcriber#6]
while starting server I get this warning
The specified config.json file /Users/shiprajain/speech/cfc-covid-19-video-transcriber/server/config/mappings.json does not exist

When I use localhost:3000 and upload a video I get this error on my console: /Explorer and /swagger/api URL not working
                                                                                                                                                                     
ERROR:root:Forbidden
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 229, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/shiprajain/speech/cfc-covid-19-video-transcriber/server/tasks.py", line 29, in process_video
    continuous=True).get_result(), indent=2
  File "/opt/anaconda3/lib/python3.7/site-packages/ibm_watson/speech_to_text_v1.py", line 466, in recognize
    response = self.send(request)
  File "/opt/anaconda3/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 229, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:48 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:49 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:49 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:49 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:49 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:49 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:50 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:50 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:50 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:50 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:50 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:50 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:50 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:50 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:50 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:31:50 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:12 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:12 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:12 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:13 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:13 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:13 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:13 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:13 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:34 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:35 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:35 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:35 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:35 +0530] [17249] [INFO] Handling signal: winch
[2020-04-05 19:34:35 +0530] [17249] [INFO] Handling signal: winch
ERROR:server:Exception on /explorer [GET]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/shiprajain/speech/cfc-covid-19-video-transcriber/server/routes/swagger.py", line 13, in explorer
    return render_template('swagger-ui/index.html')
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: swagger-ui/index.html

**Comment by pedrocruzio** [comment]
@shiprajain14 taking a look. Could you share what's your current dev environment?

cc @DanCunnington I deleted some Swagger files in the last commit. Do you think that's the cause of the issue?

**Comment by DanCunnington** [comment]
It shouldn't be @pedrocruzio  - I have also been working on this issue this morning as someone else has raised it. The API key you supplied for testing works perfectly, but new API keys created in Watson STT don't seem to authenticate correctly with the IAM authenticator.

**Comment by DanCunnington** [comment]
ah, there's two issues here. For the second issue, I'd place the swagger files back as the server is trying to render an error page. Although - it isn't required for the user interface, it's just if someone opens the server in the browser for testing.

**Comment by shiprajain14** [comment]
Yes correct , only one API key is working. when we create a new service and use the API key generated it's not working. There is already one issue like this which says this happens as service is not registered to a resource group

**Comment by DanCunnington** [comment]
Looks like this is an issue with the IBM Watson SDK - https://github.com/watson-developer-cloud/python-sdk/issues/729

**Comment by DanCunnington** [comment]
@pedrocruzio going to resolve this - could you please add those swagger files back :) thanks.
